config/routes.rb
Rails.application.routes.draw do
  root 'bank_accounts#index'
  devise_for :users
  resources :bank_accounts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  # Association
  belongs_to :user
  # you need a text column
  serialize :ledger, Array

  # Validations
  validates_presence_of :amount, :institution, :active

  # Callbacks
  before_create :initialize_ledger
  before_update :update_ledger

  private
    def initialize_ledger
      self.ledger << { ledger_change: Time.now, previous_amount: 0, new_amount: self.amount }
    end

    def update_ledger
      if self.changes[:amount]
        self.ledger << { legder_change: Time.now, previous_amount: self.changes[:amount].first, new_amount: self.amount }
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :gender, :age
  validates_inclusion_of :gender, in: %w(Male Female Other)
  validates :age, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 120 }
  has_many :bank_accounts, dependent: :destroy

  # Instance Method
  # Useage - current_user.is_old_enough?
  def is_old_enough?
    age > 16 ? true : false
  end

  # Class Methods - Also called scopes
  # Useage - index action to order all users by their age ASC
  # def index
  #   @users = User.all.by_age
  # end
  def self.by_age
    order(:age)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :gender])
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: [:show, :edit, :update, :destroy]

  # GET /bank_accounts
  def index
    @bank_accounts = current_user.bank_accounts
  end

  # GET /bank_accounts/1
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = current_user.bank_accounts.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts
  def create
    @bank_account = current_user.bank_accounts.new(bank_account_params)

    if @bank_account.save
      redirect_to @bank_account, notice: 'Bank account was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bank_accounts/1
  def update
    if @bank_account.update(bank_account_params)
      redirect_to @bank_account, notice: 'Bank account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bank_accounts/1
  def destroy
    @bank_account.destroy
    redirect_to bank_accounts_url, notice: 'Bank account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = current_user.bank_accounts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bank_account_params
      # { bank_account: {institution: 'Chase', amount: 200, active: true } }
      params.require(:bank_account).permit(:institution, :amount, :description, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bank_accounts/_form.html.haml
= form_for @bank_account, html: { id: "partial_form" } do |f|
  .field
    = f.label :institution
    = f.text_field :institution, placeholder: 'Chase'
  .field
    = f.label :description
    = f.text_area :description, placeholder: 'Your Description'
  .field
    = f.label :amount
    = f.number_field :amount
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.submit

app/views/bank_accounts/edit.html.haml
%h1
  Editing Bank Account: = @bank_account.institution
%hr

= render(partial: 'form')

= link_to 'Back', bank_account_path(@bank_account)

app/views/bank_accounts/index.html.haml
%h1 All Of My Monies
%hr
- if @bank_accounts.any?
  %ul
    - @bank_accounts.each do |bank_account|
      %li.bank-account
        %h3
          Institution:
          = link_to bank_account.institution, bank_account_path(bank_account), class: 'show-account'
        %p
          Description:
          = bank_account.description
        = link_to 'Delete', bank_account_path(bank_account), class: 'delete-account', method: :delete, data: { confirm: 'Really Delete?'}
        %hr
- else
  %h3 No Bank Accounts, Please Create One!
%br
= link_to 'New Bank Account', new_bank_account_path, id: 'new-bank-account'

app/views/bank_accounts/new.html.haml
%h1
  New Bank Account For: = current_user.email
%hr

= render(partial: 'form')

= link_to 'All Accounts', bank_accounts_path, id: 'bank-accounts'

app/views/bank_accounts/show.html.haml
%h1 = @bank_account.institution
%h3 = @bank_account.description
%hr
%h2 More Info
%hr
%h2 Current Balance: = number_to_currency(@bank_account.amount)
%h4 Ledger Transcations
%ol
  - @bank_account.ledger.each do |transaction|
    %li
      %h3
        Transaction Date:
        = transaction[:ledger_change]
      %h3
        Old Amount:
        = number_to_currency(transaction[:previous_amount])
      %h3
        New Amount:
        = number_to_currency(transaction[:new_amount])
%hr
= link_to 'Edit', edit_bank_account_path(@bank_account)
= link_to 'Back', bank_accounts_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeleniumTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>